version: '3'
services:
    postgres:
        image: postgres:latest
        environment:
            - POSTGRES_PASSWORD=password
        networks: 
            - my-network
    backend_app:
        build:
            context: ./library_back
            dockerfile: Dockerfile
        container_name: library_backend
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
            - POSTGRES_PORT=5432
            - POSTGRES_DB=postgres
            - POSTGRES_HOST=postgres
            - DJANGO_SETTINGS_MODULE=src.settings
        volumes:
            - .:/var/www
        ports:
            - 8000:8000
        networks: 
            - my-network
        depends_on:
            - postgres

    frontend_app:
        build:
            context: ./library_front
            dockerfile: Dockerfile
        container_name: library_frontend
        volumes:
            - './library_front:/app'
        ports:
            - '3000:3000'
        depends_on:
            - postgres
            - backend_app
        networks: 
            - my-network
    nginx:
        build:
            dockerfile: Dockerfile
            context: ./nginx
        image: nginx
        container_name: nginx
        ports:
            - "80:80"
        networks: 
            - my-network
        depends_on:
            - frontend_app
            - backend_app
networks: 
    my-network:
        driver: bridge